### ISSUE TITLE
Indented Headers makes Community Plugins modal unusable.

### ISSUE THREAD

**Issue by PrinceHeadache** [zamsyt/obsidian-snippets#10]
I've started using the Indented Headers snippet, which I like quite a bit. However, I've noticed two things about it:
- When disabled, headers stay indented (which is okay with me, because of the next bullet point.).
- When it's enabled, the community plugins modal slows to a complete crawl, often making Obsidian impossible to use for upwards of two minutes, in some cases.

I've included a video: the first time I press the button is with the snippet disabled, which is the expected behavior. Second time is with snippet enabled, and it has me clicking random objects on the page and hitting ESC the moment after I click the button so you can see how long it takes to register that and leave the modal.

https://github.com/zamsyt/obsidian-snippets/assets/126889088/a3a30b1e-09ef-41c8-93e3-bae033b0f569

Right now, the workaround seems to be disabling the snippet, where I keep the indented headers but don't suffer from the drawbacks in the video. 

Thanks so much! I'm taking a look at this as well, and if I can find out what's causing it, I'll update you here.

**Comment by zamsyt** [comment]
Oh my. Can confirm the issue with Community plugins. Guess I must have not noticed as I don't use the snippet all the time, and not a heavy plugin user. It might be a performance issue with the huge list of divs there, and the snippet doing checks on all divs.

**Comment by PrinceHeadache** [comment]
That's kinda what I was thinking, too. I'm currently looking into ways that I can possibly limit the snippet's behavior so it only checks for this stuff in actual notes!

**Comment by zamsyt** [comment]
Adding `.markdown-preview-view ` to the start of [line 27](https://github.com/zamsyt/obsidian-snippets/blob/1b131fb41699abd3aabcd0719440d3ec1f16cf82/src/Indent%20headings.scss#L27) makes it functional, but I'm currently looking at further optimization, since it's still inefficient and noticeably slows down the plugin and theme browsers

**Comment by zamsyt** [comment]
@PrinceHeadache can you confirm [v0.3](https://github.com/zamsyt/obsidian-snippets/blob/dev/Indent%20headings.css) fixes the issue with the Community plugins modal?

**Comment by PrinceHeadache** [comment]
Just checked it out, it seems like it does! 

Thanks so much for the quick response!
