### ISSUE TITLE
Multi-Column Notes exit columns below

### ISSUE THREAD

**Issue by j-maffe** [zamsyt/obsidian-snippets#4]
Awesome work! Is there a way to write below the columns after them or is the note completely split off into columns?

**Comment by zamsyt** [comment]
@j-maffe Not in one note with the current implementation, and I haven't found a (nice) way to do that yet. The newly added support for embeds is a kind of solution to this though --- you can add the multi-column section in an embed, and write without columns around it

**Comment by zamsyt** [comment]
I believe one option would be to create a custom callout that expands to the full note width (kind of flipping the other multicolumn implementations on their head). Ideally I could add just a marker element that escapes the columns for everything after it, but not sure if I can do that. Let me know if the callout is something that would be useful, and I'll look into adding it if possible.

**Comment by zamsyt** [comment]
@j-maffe I added support for multi-column callouts in v0.5 (different to what I suggested above, but you might find this useful for adding multicolumn sections to notes. No live preview for these though.)

**Comment by j-maffe** [comment]
This is awesome! Thanks so much! :D
But yeah I suppose having the snippet only be applied to part of the note would be quite hard, a callout is more than sufficient. Definitely much simpler and honestly better than the available plugins.
