### ISSUE TITLE
Multi-column: Broken list marker positioning

### ISSUE THREAD

**Issue by zamsyt** [zamsyt/obsidian-snippets#6]
List marker positioning (`ul`) in the first column is broken in reading view
> ![image](https://user-images.githubusercontent.com/112904909/231018486-65ca2d98-967e-4779-82df-796c54371f1a.png)
> 
> _Originally posted by @caglarongan in https://github.com/zamsyt/obsidian-snippets/issues/5#issuecomment-1502468843_

**Comment by zamsyt** [comment]
@caglarongan I fixed the list bullet alignment. It seems there might actually be a bug in Chromium here. Anyway, the default theme also uses some wonky css for this, and I replaced it with a slightly different method that doesn't have the issue.

**Comment by caglarongan** [comment]
Works perfectly, thank you :)

**Comment by caglarongan** [comment]
This fix breaks rendering for regular (not in a callout) bullet list's folding triangle in Reading Mode

https://github.com/zamsyt/obsidian-snippets/assets/112904909/3b824920-474d-46b3-b67e-3a050720bd59
