### ISSUE TITLE
Repo Request - License

### ISSUE THREAD

**Issue by sigrunixia** [zamsyt/obsidian-snippets#7]
Hello,

I may have interest in using some of these snippets within a publish site, or in other works. Your other repositories have the Unlicensed, but I did not want to assume the same applied here. Could you please update this repo with your license of choice?

**Comment by zamsyt** [comment]
Added the Unlicense. Note that I haven't tested the snippets with Publish. Browser support for some of the snippets might not be great. You're free to make bug reports here, but I can't promise I can or will fix them.

**Comment by zamsyt** [comment]
@sigrunixia To clarify the previous comment about browser support, the main concern is the `:has()` selector used in some of the snippets, as it's a new feature, and namely Firefox doesn't support it yet. It'd be appropriate to make sure such features gracefully degrade when the selector isn't available. I tried to do this to some extent with [Custom page preview](https://github.com/zamsyt/obsidian-snippets/wiki/Custom-page-preview), but haven't checked for the others using `:has()`.

**Comment by sigrunixia** [comment]
> @sigrunixia To clarify the previous comment about browser support, the main concern is the `:has()` selector used in some of the snippets, as it's a new feature, and namely Firefox doesn't support it yet. It'd be appropriate to make sure such features gracefully degrade when the selector isn't available. I tried to do this to some extent with [Custom page preview](https://github.com/zamsyt/obsidian-snippets/wiki/Custom-page-preview), but haven't checked for the others using `:has()`.

Oh no worries, and I completely understand. I simply wanted to make sure if I use some or all parts of a code, I could give proper attributions. It doesn't look good to say "Snippet (or portions of it) comes from Name" without notating I could use it in the first place.

**Comment by zamsyt** [comment]
@sigrunixia Oh right, I guess I hadn't said anything about this previously. I want people to use my creations freely and this generally applies to whatever I make.

Would you mind if I were to replace the unlicense with a less formal statement in the readme? I'm not really about the whole *copyright thing* and would prefer to just speak to humans than perpetuating lawyerspeak/this form of control. I'm happy to provide some permissive license if someone expects it, though.

**Comment by sigrunixia** [comment]
I’m perfectly fine with that. :)
