### ISSUE TITLE
Feature or Bug? Multi column View is enabled in source mode. 

### ISSUE THREAD

**Issue by sigrunixia** [zamsyt/obsidian-snippets#8]
## Feature Request or a Bug? I sure don't know! :)

In source mode, it is expected that nothing should work or change the rendering of, hence source. However, the multi column snippet continues to change the movement of text within source mode. This makes "setting up" new columns an aggravating experience. 

Otherwise, I've been having a lovely time with the snippet. It makes stuff like emulating below possible. ❤️ 

<img width="927" alt="image" src="https://github.com/zamsyt/obsidian-snippets/assets/68425372/4750a2cc-5b73-41a6-a904-d13de0b70cf7">

### Suggested "Fix" 

If it is not a bug, then I'm thinking...

- Enable a toggle via style settings.
- Or, Create a duplicate snippet that only affects reading view. 

## Obsidian Info

OS is MacOS

SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.3.5
	Operating system: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000 22.5.0
	Login status: logged in
	Catalyst license: vip
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 48
	Restricted mode: off
	Plugins installed: 33
	Plugins enabled: 0

**Comment by zamsyt** [comment]
Thanks for the feedback!

It just ended up working in source since I haven't specifically restricted the LP styles to LP only. Haven't bothered to make a decision until anyone said something. I think I can just restrict it to LP, and only add a setting if someone asks for it back in source. Can probably do it tomorrow.

**Comment by zamsyt** [comment]
@sigrunixia Does this suit your needs?

**Comment by sigrunixia** [comment]
> @sigrunixia Pushed an update. Does it suit your needs?

Yes it does! Thank you so much. <3
